export const fdata = {
  AD: { emoji: '🇦🇩', name: 'Andorra', unicode: 'U+1F1E6 U+1F1E9' },
  AE: {
    emoji: '🇦🇪',
    name: 'United Arab Emirates',
    unicode: 'U+1F1E6 U+1F1EA',
  },
  AF: { emoji: '🇦🇫', name: 'Afghanistan', unicode: 'U+1F1E6 U+1F1EB' },
  AG: {
    emoji: '🇦🇬',
    name: 'Antigua and Barbuda',
    unicode: 'U+1F1E6 U+1F1EC',
  },
  AI: { emoji: '🇦🇮', name: 'Anguilla', unicode: 'U+1F1E6 U+1F1EE' },
  AL: { emoji: '🇦🇱', name: 'Albania', unicode: 'U+1F1E6 U+1F1F1' },
  AM: { emoji: '🇦🇲', name: 'Armenia', unicode: 'U+1F1E6 U+1F1F2' },
  AO: { emoji: '🇦🇴', name: 'Angola', unicode: 'U+1F1E6 U+1F1F4' },
  AQ: { emoji: '🇦🇶', name: 'Antarctica', unicode: 'U+1F1E6 U+1F1F6' },
  AR: { emoji: '🇦🇷', name: 'Argentina', unicode: 'U+1F1E6 U+1F1F7' },
  AS: { emoji: '🇦🇸', name: 'American Samoa', unicode: 'U+1F1E6 U+1F1F8' },
  AT: { emoji: '🇦🇹', name: 'Austria', unicode: 'U+1F1E6 U+1F1F9' },
  AU: { emoji: '🇦🇺', name: 'Australia', unicode: 'U+1F1E6 U+1F1FA' },
  AW: { emoji: '🇦🇼', name: 'Aruba', unicode: 'U+1F1E6 U+1F1FC' },
  AX: { emoji: '🇦🇽', name: 'Åland Islands', unicode: 'U+1F1E6 U+1F1FD' },
  AZ: { emoji: '🇦🇿', name: 'Azerbaijan', unicode: 'U+1F1E6 U+1F1FF' },
  BA: {
    emoji: '🇧🇦',
    name: 'Bosnia and Herzegovina',
    unicode: 'U+1F1E7 U+1F1E6',
  },
  BB: { emoji: '🇧🇧', name: 'Barbados', unicode: 'U+1F1E7 U+1F1E7' },
  BD: { emoji: '🇧🇩', name: 'Bangladesh', unicode: 'U+1F1E7 U+1F1E9' },
  BE: { emoji: '🇧🇪', name: 'Belgium', unicode: 'U+1F1E7 U+1F1EA' },
  BF: { emoji: '🇧🇫', name: 'Burkina Faso', unicode: 'U+1F1E7 U+1F1EB' },
  BG: { emoji: '🇧🇬', name: 'Bulgaria', unicode: 'U+1F1E7 U+1F1EC' },
  BH: { emoji: '🇧🇭', name: 'Bahrain', unicode: 'U+1F1E7 U+1F1ED' },
  BI: { emoji: '🇧🇮', name: 'Burundi', unicode: 'U+1F1E7 U+1F1EE' },
  BJ: { emoji: '🇧🇯', name: 'Benin', unicode: 'U+1F1E7 U+1F1EF' },
  BL: {
    emoji: '🇧🇱',
    name: 'Saint Barthélemy',
    unicode: 'U+1F1E7 U+1F1F1',
  },
  BM: { emoji: '🇧🇲', name: 'Bermuda', unicode: 'U+1F1E7 U+1F1F2' },
  BN: {
    emoji: '🇧🇳',
    name: 'Brunei Darussalam',
    unicode: 'U+1F1E7 U+1F1F3',
  },
  BO: { emoji: '🇧🇴', name: 'Bolivia', unicode: 'U+1F1E7 U+1F1F4' },
  BQ: {
    emoji: '🇧🇶',
    name: 'Bonaire, Sint Eustatius and Saba',
    unicode: 'U+1F1E7 U+1F1F6',
  },
  BR: { emoji: '🇧🇷', name: 'Brazil', unicode: 'U+1F1E7 U+1F1F7' },
  BS: { emoji: '🇧🇸', name: 'Bahamas', unicode: 'U+1F1E7 U+1F1F8' },
  BT: { emoji: '🇧🇹', name: 'Bhutan', unicode: 'U+1F1E7 U+1F1F9' },
  BV: { emoji: '🇧🇻', name: 'Bouvet Island', unicode: 'U+1F1E7 U+1F1FB' },
  BW: { emoji: '🇧🇼', name: 'Botswana', unicode: 'U+1F1E7 U+1F1FC' },
  BY: { emoji: '🇧🇾', name: 'Belarus', unicode: 'U+1F1E7 U+1F1FE' },
  BZ: { emoji: '🇧🇿', name: 'Belize', unicode: 'U+1F1E7 U+1F1FF' },
  CA: { emoji: '🇨🇦', name: 'Canada', unicode: 'U+1F1E8 U+1F1E6' },
  CC: {
    emoji: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    unicode: 'U+1F1E8 U+1F1E8',
  },
  CD: { emoji: '🇨🇩', name: 'Congo', unicode: 'U+1F1E8 U+1F1E9' },
  CF: {
    emoji: '🇨🇫',
    name: 'Central African Republic',
    unicode: 'U+1F1E8 U+1F1EB',
  },
  CG: { emoji: '🇨🇬', name: 'Congo', unicode: 'U+1F1E8 U+1F1EC' },
  CH: { emoji: '🇨🇭', name: 'Switzerland', unicode: 'U+1F1E8 U+1F1ED' },
  CI: { emoji: '🇨🇮', name: "Côte D'Ivoire", unicode: 'U+1F1E8 U+1F1EE' },
  CK: { emoji: '🇨🇰', name: 'Cook Islands', unicode: 'U+1F1E8 U+1F1F0' },
  CL: { emoji: '🇨🇱', name: 'Chile', unicode: 'U+1F1E8 U+1F1F1' },
  CM: { emoji: '🇨🇲', name: 'Cameroon', unicode: 'U+1F1E8 U+1F1F2' },
  CN: { emoji: '🇨🇳', name: 'China', unicode: 'U+1F1E8 U+1F1F3' },
  CO: { emoji: '🇨🇴', name: 'Colombia', unicode: 'U+1F1E8 U+1F1F4' },
  CR: { emoji: '🇨🇷', name: 'Costa Rica', unicode: 'U+1F1E8 U+1F1F7' },
  CU: { emoji: '🇨🇺', name: 'Cuba', unicode: 'U+1F1E8 U+1F1FA' },
  CV: { emoji: '🇨🇻', name: 'Cape Verde', unicode: 'U+1F1E8 U+1F1FB' },
  CW: { emoji: '🇨🇼', name: 'Curaçao', unicode: 'U+1F1E8 U+1F1FC' },
  CX: {
    emoji: '🇨🇽',
    name: 'Christmas Island',
    unicode: 'U+1F1E8 U+1F1FD',
  },
  CY: { emoji: '🇨🇾', name: 'Cyprus', unicode: 'U+1F1E8 U+1F1FE' },
  CZ: { emoji: '🇨🇿', name: 'Czech Republic', unicode: 'U+1F1E8 U+1F1FF' },
  DE: { emoji: '🇩🇪', name: 'Germany', unicode: 'U+1F1E9 U+1F1EA' },
  DJ: { emoji: '🇩🇯', name: 'Djibouti', unicode: 'U+1F1E9 U+1F1EF' },
  DK: { emoji: '🇩🇰', name: 'Denmark', unicode: 'U+1F1E9 U+1F1F0' },
  DM: { emoji: '🇩🇲', name: 'Dominica', unicode: 'U+1F1E9 U+1F1F2' },
  DO: {
    emoji: '🇩🇴',
    name: 'Dominican Republic',
    unicode: 'U+1F1E9 U+1F1F4',
  },
  DZ: { emoji: '🇩🇿', name: 'Algeria', unicode: 'U+1F1E9 U+1F1FF' },
  EC: { emoji: '🇪🇨', name: 'Ecuador', unicode: 'U+1F1EA U+1F1E8' },
  EE: { emoji: '🇪🇪', name: 'Estonia', unicode: 'U+1F1EA U+1F1EA' },
  EG: { emoji: '🇪🇬', name: 'Egypt', unicode: 'U+1F1EA U+1F1EC' },
  EH: { emoji: '🇪🇭', name: 'Western Sahara', unicode: 'U+1F1EA U+1F1ED' },
  ER: { emoji: '🇪🇷', name: 'Eritrea', unicode: 'U+1F1EA U+1F1F7' },
  ES: { emoji: '🇪🇸', name: 'Spain', unicode: 'U+1F1EA U+1F1F8' },
  ET: { emoji: '🇪🇹', name: 'Ethiopia', unicode: 'U+1F1EA U+1F1F9' },
  EU: { emoji: '🇪🇺', name: 'European Union', unicode: 'U+1F1EA U+1F1FA' },
  FI: { emoji: '🇫🇮', name: 'Finland', unicode: 'U+1F1EB U+1F1EE' },
  FJ: { emoji: '🇫🇯', name: 'Fiji', unicode: 'U+1F1EB U+1F1EF' },
  FK: {
    emoji: '🇫🇰',
    name: 'Falkland Islands (Malvinas)',
    unicode: 'U+1F1EB U+1F1F0',
  },
  FM: { emoji: '🇫🇲', name: 'Micronesia', unicode: 'U+1F1EB U+1F1F2' },
  FO: { emoji: '🇫🇴', name: 'Faroe Islands', unicode: 'U+1F1EB U+1F1F4' },
  FR: { emoji: '🇫🇷', name: 'France', unicode: 'U+1F1EB U+1F1F7' },
  GA: { emoji: '🇬🇦', name: 'Gabon', unicode: 'U+1F1EC U+1F1E6' },
  GB: { emoji: '🇬🇧', name: 'United Kingdom', unicode: 'U+1F1EC U+1F1E7' },
  GD: { emoji: '🇬🇩', name: 'Grenada', unicode: 'U+1F1EC U+1F1E9' },
  GE: { emoji: '🇬🇪', name: 'Georgia', unicode: 'U+1F1EC U+1F1EA' },
  GF: { emoji: '🇬🇫', name: 'French Guiana', unicode: 'U+1F1EC U+1F1EB' },
  GG: { emoji: '🇬🇬', name: 'Guernsey', unicode: 'U+1F1EC U+1F1EC' },
  GH: { emoji: '🇬🇭', name: 'Ghana', unicode: 'U+1F1EC U+1F1ED' },
  GI: { emoji: '🇬🇮', name: 'Gibraltar', unicode: 'U+1F1EC U+1F1EE' },
  GL: { emoji: '🇬🇱', name: 'Greenland', unicode: 'U+1F1EC U+1F1F1' },
  GM: { emoji: '🇬🇲', name: 'Gambia', unicode: 'U+1F1EC U+1F1F2' },
  GN: { emoji: '🇬🇳', name: 'Guinea', unicode: 'U+1F1EC U+1F1F3' },
  GP: { emoji: '🇬🇵', name: 'Guadeloupe', unicode: 'U+1F1EC U+1F1F5' },
  GQ: {
    emoji: '🇬🇶',
    name: 'Equatorial Guinea',
    unicode: 'U+1F1EC U+1F1F6',
  },
  GR: { emoji: '🇬🇷', name: 'Greece', unicode: 'U+1F1EC U+1F1F7' },
  GS: { emoji: '🇬🇸', name: 'South Georgia', unicode: 'U+1F1EC U+1F1F8' },
  GT: { emoji: '🇬🇹', name: 'Guatemala', unicode: 'U+1F1EC U+1F1F9' },
  GU: { emoji: '🇬🇺', name: 'Guam', unicode: 'U+1F1EC U+1F1FA' },
  GW: { emoji: '🇬🇼', name: 'Guinea-Bissau', unicode: 'U+1F1EC U+1F1FC' },
  GY: { emoji: '🇬🇾', name: 'Guyana', unicode: 'U+1F1EC U+1F1FE' },
  HK: { emoji: '🇭🇰', name: 'Hong Kong', unicode: 'U+1F1ED U+1F1F0' },
  HM: {
    emoji: '🇭🇲',
    name: 'Heard Island and Mcdonald Islands',
    unicode: 'U+1F1ED U+1F1F2',
  },
  HN: { emoji: '🇭🇳', name: 'Honduras', unicode: 'U+1F1ED U+1F1F3' },
  HR: { emoji: '🇭🇷', name: 'Croatia', unicode: 'U+1F1ED U+1F1F7' },
  HT: { emoji: '🇭🇹', name: 'Haiti', unicode: 'U+1F1ED U+1F1F9' },
  HU: { emoji: '🇭🇺', name: 'Hungary', unicode: 'U+1F1ED U+1F1FA' },
  ID: { emoji: '🇮🇩', name: 'Indonesia', unicode: 'U+1F1EE U+1F1E9' },
  IE: { emoji: '🇮🇪', name: 'Ireland', unicode: 'U+1F1EE U+1F1EA' },
  IL: { emoji: '🇮🇱', name: 'Israel', unicode: 'U+1F1EE U+1F1F1' },
  IM: { emoji: '🇮🇲', name: 'Isle of Man', unicode: 'U+1F1EE U+1F1F2' },
  IN: { emoji: '🇮🇳', name: 'India', unicode: 'U+1F1EE U+1F1F3' },
  IO: {
    emoji: '🇮🇴',
    name: 'British Indian Ocean Territory',
    unicode: 'U+1F1EE U+1F1F4',
  },
  IQ: { emoji: '🇮🇶', name: 'Iraq', unicode: 'U+1F1EE U+1F1F6' },
  IR: { emoji: '🇮🇷', name: 'Iran', unicode: 'U+1F1EE U+1F1F7' },
  IS: { emoji: '🇮🇸', name: 'Iceland', unicode: 'U+1F1EE U+1F1F8' },
  IT: { emoji: '🇮🇹', name: 'Italy', unicode: 'U+1F1EE U+1F1F9' },
  JE: { emoji: '🇯🇪', name: 'Jersey', unicode: 'U+1F1EF U+1F1EA' },
  JM: { emoji: '🇯🇲', name: 'Jamaica', unicode: 'U+1F1EF U+1F1F2' },
  JO: { emoji: '🇯🇴', name: 'Jordan', unicode: 'U+1F1EF U+1F1F4' },
  JP: { emoji: '🇯🇵', name: 'Japan', unicode: 'U+1F1EF U+1F1F5' },
  KE: { emoji: '🇰🇪', name: 'Kenya', unicode: 'U+1F1F0 U+1F1EA' },
  KG: { emoji: '🇰🇬', name: 'Kyrgyzstan', unicode: 'U+1F1F0 U+1F1EC' },
  KH: { emoji: '🇰🇭', name: 'Cambodia', unicode: 'U+1F1F0 U+1F1ED' },
  KI: { emoji: '🇰🇮', name: 'Kiribati', unicode: 'U+1F1F0 U+1F1EE' },
  KM: { emoji: '🇰🇲', name: 'Comoros', unicode: 'U+1F1F0 U+1F1F2' },
  KN: {
    emoji: '🇰🇳',
    name: 'Saint Kitts and Nevis',
    unicode: 'U+1F1F0 U+1F1F3',
  },
  KP: { emoji: '🇰🇵', name: 'North Korea', unicode: 'U+1F1F0 U+1F1F5' },
  KR: { emoji: '🇰🇷', name: 'South Korea', unicode: 'U+1F1F0 U+1F1F7' },
  KW: { emoji: '🇰🇼', name: 'Kuwait', unicode: 'U+1F1F0 U+1F1FC' },
  KY: { emoji: '🇰🇾', name: 'Cayman Islands', unicode: 'U+1F1F0 U+1F1FE' },
  KZ: { emoji: '🇰🇿', name: 'Kazakhstan', unicode: 'U+1F1F0 U+1F1FF' },
  LA: {
    emoji: '🇱🇦',
    name: "Lao People's Democratic Republic",
    unicode: 'U+1F1F1 U+1F1E6',
  },
  LB: { emoji: '🇱🇧', name: 'Lebanon', unicode: 'U+1F1F1 U+1F1E7' },
  LC: { emoji: '🇱🇨', name: 'Saint Lucia', unicode: 'U+1F1F1 U+1F1E8' },
  LI: { emoji: '🇱🇮', name: 'Liechtenstein', unicode: 'U+1F1F1 U+1F1EE' },
  LK: { emoji: '🇱🇰', name: 'Sri Lanka', unicode: 'U+1F1F1 U+1F1F0' },
  LR: { emoji: '🇱🇷', name: 'Liberia', unicode: 'U+1F1F1 U+1F1F7' },
  LS: { emoji: '🇱🇸', name: 'Lesotho', unicode: 'U+1F1F1 U+1F1F8' },
  LT: { emoji: '🇱🇹', name: 'Lithuania', unicode: 'U+1F1F1 U+1F1F9' },
  LU: { emoji: '🇱🇺', name: 'Luxembourg', unicode: 'U+1F1F1 U+1F1FA' },
  LV: { emoji: '🇱🇻', name: 'Latvia', unicode: 'U+1F1F1 U+1F1FB' },
  LY: { emoji: '🇱🇾', name: 'Libya', unicode: 'U+1F1F1 U+1F1FE' },
  MA: { emoji: '🇲🇦', name: 'Morocco', unicode: 'U+1F1F2 U+1F1E6' },
  MC: { emoji: '🇲🇨', name: 'Monaco', unicode: 'U+1F1F2 U+1F1E8' },
  MD: { emoji: '🇲🇩', name: 'Moldova', unicode: 'U+1F1F2 U+1F1E9' },
  ME: { emoji: '🇲🇪', name: 'Montenegro', unicode: 'U+1F1F2 U+1F1EA' },
  MF: {
    emoji: '🇲🇫',
    name: 'Saint Martin (French Part)',
    unicode: 'U+1F1F2 U+1F1EB',
  },
  MG: { emoji: '🇲🇬', name: 'Madagascar', unicode: 'U+1F1F2 U+1F1EC' },
  MH: {
    emoji: '🇲🇭',
    name: 'Marshall Islands',
    unicode: 'U+1F1F2 U+1F1ED',
  },
  MK: { emoji: '🇲🇰', name: 'Macedonia', unicode: 'U+1F1F2 U+1F1F0' },
  ML: { emoji: '🇲🇱', name: 'Mali', unicode: 'U+1F1F2 U+1F1F1' },
  MM: { emoji: '🇲🇲', name: 'Myanmar', unicode: 'U+1F1F2 U+1F1F2' },
  MN: { emoji: '🇲🇳', name: 'Mongolia', unicode: 'U+1F1F2 U+1F1F3' },
  MO: { emoji: '🇲🇴', name: 'Macao', unicode: 'U+1F1F2 U+1F1F4' },
  MP: {
    emoji: '🇲🇵',
    name: 'Northern Mariana Islands',
    unicode: 'U+1F1F2 U+1F1F5',
  },
  MQ: { emoji: '🇲🇶', name: 'Martinique', unicode: 'U+1F1F2 U+1F1F6' },
  MR: { emoji: '🇲🇷', name: 'Mauritania', unicode: 'U+1F1F2 U+1F1F7' },
  MS: { emoji: '🇲🇸', name: 'Montserrat', unicode: 'U+1F1F2 U+1F1F8' },
  MT: { emoji: '🇲🇹', name: 'Malta', unicode: 'U+1F1F2 U+1F1F9' },
  MU: { emoji: '🇲🇺', name: 'Mauritius', unicode: 'U+1F1F2 U+1F1FA' },
  MV: { emoji: '🇲🇻', name: 'Maldives', unicode: 'U+1F1F2 U+1F1FB' },
  MW: { emoji: '🇲🇼', name: 'Malawi', unicode: 'U+1F1F2 U+1F1FC' },
  MX: { emoji: '🇲🇽', name: 'Mexico', unicode: 'U+1F1F2 U+1F1FD' },
  MY: { emoji: '🇲🇾', name: 'Malaysia', unicode: 'U+1F1F2 U+1F1FE' },
  MZ: { emoji: '🇲🇿', name: 'Mozambique', unicode: 'U+1F1F2 U+1F1FF' },
  NA: { emoji: '🇳🇦', name: 'Namibia', unicode: 'U+1F1F3 U+1F1E6' },
  NC: { emoji: '🇳🇨', name: 'New Caledonia', unicode: 'U+1F1F3 U+1F1E8' },
  NE: { emoji: '🇳🇪', name: 'Niger', unicode: 'U+1F1F3 U+1F1EA' },
  NF: { emoji: '🇳🇫', name: 'Norfolk Island', unicode: 'U+1F1F3 U+1F1EB' },
  NG: { emoji: '🇳🇬', name: 'Nigeria', unicode: 'U+1F1F3 U+1F1EC' },
  NI: { emoji: '🇳🇮', name: 'Nicaragua', unicode: 'U+1F1F3 U+1F1EE' },
  NL: { emoji: '🇳🇱', name: 'Netherlands', unicode: 'U+1F1F3 U+1F1F1' },
  NO: { emoji: '🇳🇴', name: 'Norway', unicode: 'U+1F1F3 U+1F1F4' },
  NP: { emoji: '🇳🇵', name: 'Nepal', unicode: 'U+1F1F3 U+1F1F5' },
  NR: { emoji: '🇳🇷', name: 'Nauru', unicode: 'U+1F1F3 U+1F1F7' },
  NU: { emoji: '🇳🇺', name: 'Niue', unicode: 'U+1F1F3 U+1F1FA' },
  NZ: { emoji: '🇳🇿', name: 'New Zealand', unicode: 'U+1F1F3 U+1F1FF' },
  OM: { emoji: '🇴🇲', name: 'Oman', unicode: 'U+1F1F4 U+1F1F2' },
  PA: { emoji: '🇵🇦', name: 'Panama', unicode: 'U+1F1F5 U+1F1E6' },
  PE: { emoji: '🇵🇪', name: 'Peru', unicode: 'U+1F1F5 U+1F1EA' },
  PF: {
    emoji: '🇵🇫',
    name: 'French Polynesia',
    unicode: 'U+1F1F5 U+1F1EB',
  },
  PG: {
    emoji: '🇵🇬',
    name: 'Papua New Guinea',
    unicode: 'U+1F1F5 U+1F1EC',
  },
  PH: { emoji: '🇵🇭', name: 'Philippines', unicode: 'U+1F1F5 U+1F1ED' },
  PK: { emoji: '🇵🇰', name: 'Pakistan', unicode: 'U+1F1F5 U+1F1F0' },
  PL: { emoji: '🇵🇱', name: 'Poland', unicode: 'U+1F1F5 U+1F1F1' },
  PM: {
    emoji: '🇵🇲',
    name: 'Saint Pierre and Miquelon',
    unicode: 'U+1F1F5 U+1F1F2',
  },
  PN: { emoji: '🇵🇳', name: 'Pitcairn', unicode: 'U+1F1F5 U+1F1F3' },
  PR: { emoji: '🇵🇷', name: 'Puerto Rico', unicode: 'U+1F1F5 U+1F1F7' },
  PS: {
    emoji: '🇵🇸',
    name: 'Palestinian Territory',
    unicode: 'U+1F1F5 U+1F1F8',
  },
  PT: { emoji: '🇵🇹', name: 'Portugal', unicode: 'U+1F1F5 U+1F1F9' },
  PW: { emoji: '🇵🇼', name: 'Palau', unicode: 'U+1F1F5 U+1F1FC' },
  PY: { emoji: '🇵🇾', name: 'Paraguay', unicode: 'U+1F1F5 U+1F1FE' },
  QA: { emoji: '🇶🇦', name: 'Qatar', unicode: 'U+1F1F6 U+1F1E6' },
  RE: { emoji: '🇷🇪', name: 'Réunion', unicode: 'U+1F1F7 U+1F1EA' },
  RO: { emoji: '🇷🇴', name: 'Romania', unicode: 'U+1F1F7 U+1F1F4' },
  RS: { emoji: '🇷🇸', name: 'Serbia', unicode: 'U+1F1F7 U+1F1F8' },
  RU: { emoji: '🇷🇺', name: 'Russia', unicode: 'U+1F1F7 U+1F1FA' },
  RW: { emoji: '🇷🇼', name: 'Rwanda', unicode: 'U+1F1F7 U+1F1FC' },
  SA: { emoji: '🇸🇦', name: 'Saudi Arabia', unicode: 'U+1F1F8 U+1F1E6' },
  SB: {
    emoji: '🇸🇧',
    name: 'Solomon Islands',
    unicode: 'U+1F1F8 U+1F1E7',
  },
  SC: { emoji: '🇸🇨', name: 'Seychelles', unicode: 'U+1F1F8 U+1F1E8' },
  SD: { emoji: '🇸🇩', name: 'Sudan', unicode: 'U+1F1F8 U+1F1E9' },
  SE: { emoji: '🇸🇪', name: 'Sweden', unicode: 'U+1F1F8 U+1F1EA' },
  SG: { emoji: '🇸🇬', name: 'Singapore', unicode: 'U+1F1F8 U+1F1EC' },
  SH: {
    emoji: '🇸🇭',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    unicode: 'U+1F1F8 U+1F1ED',
  },
  SI: { emoji: '🇸🇮', name: 'Slovenia', unicode: 'U+1F1F8 U+1F1EE' },
  SJ: {
    emoji: '🇸🇯',
    name: 'Svalbard and Jan Mayen',
    unicode: 'U+1F1F8 U+1F1EF',
  },
  SK: { emoji: '🇸🇰', name: 'Slovakia', unicode: 'U+1F1F8 U+1F1F0' },
  SL: { emoji: '🇸🇱', name: 'Sierra Leone', unicode: 'U+1F1F8 U+1F1F1' },
  SM: { emoji: '🇸🇲', name: 'San Marino', unicode: 'U+1F1F8 U+1F1F2' },
  SN: { emoji: '🇸🇳', name: 'Senegal', unicode: 'U+1F1F8 U+1F1F3' },
  SO: { emoji: '🇸🇴', name: 'Somalia', unicode: 'U+1F1F8 U+1F1F4' },
  SR: { emoji: '🇸🇷', name: 'Suriname', unicode: 'U+1F1F8 U+1F1F7' },
  SS: { emoji: '🇸🇸', name: 'South Sudan', unicode: 'U+1F1F8 U+1F1F8' },
  ST: {
    emoji: '🇸🇹',
    name: 'Sao Tome and Principe',
    unicode: 'U+1F1F8 U+1F1F9',
  },
  SV: { emoji: '🇸🇻', name: 'El Salvador', unicode: 'U+1F1F8 U+1F1FB' },
  SX: {
    emoji: '🇸🇽',
    name: 'Sint Maarten (Dutch Part)',
    unicode: 'U+1F1F8 U+1F1FD',
  },
  SY: {
    emoji: '🇸🇾',
    name: 'Syrian Arab Republic',
    unicode: 'U+1F1F8 U+1F1FE',
  },
  SZ: { emoji: '🇸🇿', name: 'Swaziland', unicode: 'U+1F1F8 U+1F1FF' },
  TC: {
    emoji: '🇹🇨',
    name: 'Turks and Caicos Islands',
    unicode: 'U+1F1F9 U+1F1E8',
  },
  TD: { emoji: '🇹🇩', name: 'Chad', unicode: 'U+1F1F9 U+1F1E9' },
  TF: {
    emoji: '🇹🇫',
    name: 'French Southern Territories',
    unicode: 'U+1F1F9 U+1F1EB',
  },
  TG: { emoji: '🇹🇬', name: 'Togo', unicode: 'U+1F1F9 U+1F1EC' },
  TH: { emoji: '🇹🇭', name: 'Thailand', unicode: 'U+1F1F9 U+1F1ED' },
  TJ: { emoji: '🇹🇯', name: 'Tajikistan', unicode: 'U+1F1F9 U+1F1EF' },
  TK: { emoji: '🇹🇰', name: 'Tokelau', unicode: 'U+1F1F9 U+1F1F0' },
  TL: { emoji: '🇹🇱', name: 'Timor-Leste', unicode: 'U+1F1F9 U+1F1F1' },
  TM: { emoji: '🇹🇲', name: 'Turkmenistan', unicode: 'U+1F1F9 U+1F1F2' },
  TN: { emoji: '🇹🇳', name: 'Tunisia', unicode: 'U+1F1F9 U+1F1F3' },
  TO: { emoji: '🇹🇴', name: 'Tonga', unicode: 'U+1F1F9 U+1F1F4' },
  TR: { emoji: '🇹🇷', name: 'Turkey', unicode: 'U+1F1F9 U+1F1F7' },
  TT: {
    emoji: '🇹🇹',
    name: 'Trinidad and Tobago',
    unicode: 'U+1F1F9 U+1F1F9',
  },
  TV: { emoji: '🇹🇻', name: 'Tuvalu', unicode: 'U+1F1F9 U+1F1FB' },
  TW: { emoji: '🇹🇼', name: 'Taiwan', unicode: 'U+1F1F9 U+1F1FC' },
  TZ: { emoji: '🇹🇿', name: 'Tanzania', unicode: 'U+1F1F9 U+1F1FF' },
  UA: { emoji: '🇺🇦', name: 'Ukraine', unicode: 'U+1F1FA U+1F1E6' },
  UG: { emoji: '🇺🇬', name: 'Uganda', unicode: 'U+1F1FA U+1F1EC' },
  UM: {
    emoji: '🇺🇲',
    name: 'United States Minor Outlying Islands',
    unicode: 'U+1F1FA U+1F1F2',
  },
  US: { emoji: '🇺🇸', name: 'United States', unicode: 'U+1F1FA U+1F1F8' },
  UY: { emoji: '🇺🇾', name: 'Uruguay', unicode: 'U+1F1FA U+1F1FE' },
  UZ: { emoji: '🇺🇿', name: 'Uzbekistan', unicode: 'U+1F1FA U+1F1FF' },
  VA: { emoji: '🇻🇦', name: 'Vatican City', unicode: 'U+1F1FB U+1F1E6' },
  VC: {
    emoji: '🇻🇨',
    name: 'Saint Vincent and The Grenadines',
    unicode: 'U+1F1FB U+1F1E8',
  },
  VE: { emoji: '🇻🇪', name: 'Venezuela', unicode: 'U+1F1FB U+1F1EA' },
  VG: {
    emoji: '🇻🇬',
    name: 'Virgin Islands, British',
    unicode: 'U+1F1FB U+1F1EC',
  },
  VI: {
    emoji: '🇻🇮',
    name: 'Virgin Islands, U.S.',
    unicode: 'U+1F1FB U+1F1EE',
  },
  VN: { emoji: '🇻🇳', name: 'Viet Nam', unicode: 'U+1F1FB U+1F1F3' },
  VU: { emoji: '🇻🇺', name: 'Vanuatu', unicode: 'U+1F1FB U+1F1FA' },
  WF: {
    emoji: '🇼🇫',
    name: 'Wallis and Futuna',
    unicode: 'U+1F1FC U+1F1EB',
  },
  WS: { emoji: '🇼🇸', name: 'Samoa', unicode: 'U+1F1FC U+1F1F8' },
  XK: { emoji: '🇽🇰', name: 'Kosovo', unicode: 'U+1F1FD U+1F1F0' },
  YE: { emoji: '🇾🇪', name: 'Yemen', unicode: 'U+1F1FE U+1F1EA' },
  YT: { emoji: '🇾🇹', name: 'Mayotte', unicode: 'U+1F1FE U+1F1F9' },
  ZA: { emoji: '🇿🇦', name: 'South Africa', unicode: 'U+1F1FF U+1F1E6' },
  ZM: { emoji: '🇿🇲', name: 'Zambia', unicode: 'U+1F1FF U+1F1F2' },
  ZW: { emoji: '🇿🇼', name: 'Zimbabwe', unicode: 'U+1F1FF U+1F1FC' },
};
